FROM node:20-alpine

RUN apk add --no-cache libc6-compat

WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./

# Install dependencies
RUN npm install

# Copy rest of the files
COPY . .

ENV NEXT_TELEMETRY_DISABLED 1

EXPOSE 3003

ENV PORT 3003
ENV HOSTNAME "0.0.0.0"

CMD ["npm", "run", "dev", "--", "-H", "0.0.0.0"]

